version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2021-09-23T04-46-24Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"

  jupyter-pyflink:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
    environment:
      - FLINK_HOME=/opt/flink
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
