version: '3'
services:
  mariadb:
    image: 'coomia/mariadb:10.6.5'
    hostname: mariadb
    ports:
      - '3306:3306'
    volumes:
     - ./data/maria/:/var/lib/mysql
     - ./conf/maria/config/my.cnf:/etc/mysql/my.cnf
     - ./conf/maria/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hmsdb
    healthcheck:
      test: "/usr/bin/mysql --user=admin --password=admin --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - ngdbp-network

  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - ngdbp-network

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    networks:
      - ngdbp-network
    volumes:
      - ./data:/tmp/data
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/lakehouse;
      /usr/bin/mc mb minio/lakehouse;
      /usr/bin/mc policy set public minio/lakehouse;
      /usr/bin/mc cp -r /tmp/data/* minio/lakehouse;
      exit 0; " 

  jobmanager:
    image: coomia/flink-iceberg-minio:1.16.1.01
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
        state.backend: filesystem
        state.checkpoints.dir: s3://state/checkpoint
        s3.endpoint: http://minio:9000
        s3.path.style.access: true
        s3.access-key: minio
        s3.secret-key: minio123
    networks:
      - ngdbp-network

  taskmanager:
    image: coomia/flink-iceberg-minio:1.16.1.01
    links:
      - jobmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2        
        state.backend: filesystem
        state.checkpoints.dir: s3://state/checkpoint
        s3.endpoint: http://minio:9000
        s3.path.style.access: true
        s3.access-key: minio
        s3.secret-key: minio123
    networks:
      - ngdbp-network

volumes:
  minio-data:
    driver: local

networks:
  ngdbp-network:
    driver: bridge